### ISSUE TITLE
Keep sub-entries expanded when stepping through code

### ISSUE THREAD

**Issue by igorlfs** [rcarriga/nvim-dap-ui#97]
Stepping collapses sub-entries, eg
![image](https://user-images.githubusercontent.com/84649544/164909656-b6608d5e-5c56-4c4e-aeb2-d34d449b4af4.png)
becomes
![image](https://user-images.githubusercontent.com/84649544/164909676-2ba22305-0594-4e24-b41a-b06fff18fe3c.png)

**Comment by rcarriga** [comment]
I'm not seeing the same behaviour. Can you supply a reproduction (including nvim-dap config/adapter settings)?

**Comment by igorlfs** [comment]
> I'm not seeing the same behaviour.

Whoops, should have been more clear with a reproduction 😅 

> Can you supply a reproduction (including nvim-dap config/adapter settings)?

I've tested with 2 adapters. The original one was lldb-vscode, with the following:

<details>
  <summary>adapter settings</summary>
  
```
dap.adapters.lldb = {
    type = "executable",
    command = "/usr/bin/lldb-vscode",
    name = "lldb",
}
```
</details>

and

<details>
  <summary> config </summary>
  
```
dap.configurations.cpp = {
    {
        name = "Launch",
        type = "lldb",
        request = "launch",
        program = vim.fn.getcwd() .. "/binary",
        cwd = vim.fn.getcwd(),
        stopOnEntry = false,
    },
}

```
</details>

Additionally, I also decided to test with debugpy:

<details>
  <summary>(adapter settings)</summary>
  
```
dap.adapters.python = {
    type = "executable";
    command = "/usr/bin/python3";
    args = { "-m", "debugpy.adapter" };
}
```
</details>


<details>
  <summary>(config)</summary>
  
```
dap.configurations.python = {
    {
        type = "python";
        request = "launch";
        name = "Launch file";

        program = "${file}";
        pythonPath = "/usr/bin/python"
    },
}
```
</details>

 With debugpy, I observed a different behavior: while sub-entries don't get collapsed when stepping, they also don't get updated, needing to be manually closed and opened to become so.

**Comment by rcarriga** [comment]
OK I've fixed the issue for Python anyway and believe it'll fix the lldb-vscode. Let me know if not :smile:

**Comment by igorlfs** [comment]
Hey, thanks for fixing the issue with debugpy! Unfortunately, I'm still having the issue with lldb-vscode :(

I can record a demo if you think that it would be helpful.

**Comment by rcarriga** [comment]
OK I don't use C++ but managed to reproduce it with Rust (forgot they used the same adapter). I believe this is actually an lldb issue but managed to find a workaround. Please try the latest commit

**Comment by igorlfs** [comment]
> Please try the latest commit

Apparently it's working but I still want to investigate a little further. I think under some circunstances a visual glitch may happen where a collapsed entry expands, overlaping with the actually expandend entries (I'm unsure how to reproduce this). Feel free to close this issue though, as I think this behavior is unrelated and the main problem I had was solved. Thanks for the amazing job :)

> I believe this is actually an lldb issue

Should I file a bug report on llvm's repo?

**Comment by rcarriga** [comment]
> I think under some circunstances a visual glitch may happen where a collapsed entry expands, overlaping with the actually expandend entries (I'm unsure how to reproduce this)

If you turn on nvim-dap debug logs and see it happen again, I should be able to spot the cause. Happy to keep open for a while anyway.

> Should I file a bug report on llvm's repo?

You could but it's a weird bug and I didn't try reproducing with the CLI (which I imagine they'll want). I wasn't able to reproduce with VSCode either. The issue occurring was that the adapter was responding to the `variables` request of the list element (in your screenshot `c[0]` with no variables meaning they are empty. This only happened after stepping once, and then it would respond with the correct data for following steps. It was pretty odd. Once I get a bit of time I could try put together a reproduction

**Comment by igorlfs** [comment]
I've managed to find a way to reproduce the aforementioned visual glitch:
1. Set a breakpoint and start a debugging session normally
2. Add a variable to the watch list and fully expand it
3. Add a second variable to the watch list, but only toggle it's first layer, eg
![image](https://user-images.githubusercontent.com/84649544/172962542-eaf6ed61-dcbb-4407-853a-0342abee14af.png)
4. Step through the code such that the second variable's collapsed members change. Now you get this:
![image](https://user-images.githubusercontent.com/84649544/172962993-0a192c50-3b90-4177-9d71-bc0dd4421e35.png)
Here's the nvim-dap [log](https://gist.github.com/igorlfs/01e29bd786992569505dc4816075be19)

**Comment by rcarriga** [comment]
Thanks for that, I was able to reproduce. I haven't had the time to figure out the issue but will take a look when I can

**Comment by rcarriga** [comment]
OK should be working now :sweat_smile:

**Comment by igorlfs** [comment]
Everything is working perfectly now, thank you!
